### ISSUE TITLE
Task 4 - use of "it" more idiomatic Kotlin?

### ISSUE THREAD

**Issue by alexconlin** [Kotlin/kotlin-koans#106]
Do you think using `it` in the lambda would be more idiomatic Kotlin? I will make a PR if people agree with me.

e.g.

```collection.any { it % 2 == 0 }```

**Comment by alexconlin** [comment]
made pr anyway having read https://kotlinlang.org/docs/reference/coding-conventions.html#lambdas

**Comment by svtk** [comment]
Merged
