### ISSUE TITLE
Mixed up encoding of months

### ISSUE THREAD

**Issue by angelsanz** [Kotlin/kotlin-koans#110]
[Here](https://github.com/Kotlin/kotlin-koans/blob/master/test/iii_conventions/N29OperatorsOverloadingKtTest.kt#L8) it is claimed that months are numbered starting by 0.

[Here](https://github.com/Kotlin/kotlin-koans/blob/master/test/iii_conventions/N30DestructuringDeclarationsKtTest.kt#L9) `2` is supposed to mean 'February'.

**Comment by svtk** [comment]
Fixed, thanks
