### ISSUE TITLE
Could not determine java version from '9.0.0.15'

### ISSUE THREAD

**Issue by rlindooren** [Kotlin/kotlin-koans#115]
I opened the Koans project in IntelliJ but noticed that the `build.gradle` file couldn't be parsed.

When clicking on the 'Refresh all Gradle projects' button in the 'Gradle Projects' menu I got the following message: 'Could not determine java version from '9.0.0.15''.

After upgrading Gradle to version 4.2.1 the problem went away and the contents of the build.gradle file were recognized correctly.
I found the solution here: https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457/3

PR: https://github.com/Kotlin/kotlin-koans/pull/114

**Comment by svtk** [comment]
#114 merged
