### ISSUE TITLE
Utilize MyDate.nextDay() in Task 28 Resolution

### ISSUE THREAD

**Issue by jordan-roath** [Kotlin/kotlin-koans#119]
The instructions for [task 28](https://github.com/Kotlin/kotlin-koans/blob/master/src/iii_conventions/n28ForLoop.kt) suggests that `MyDate.nextDay()` should be utilized.  The [`DateIterator` in the resolution](https://github.com/Kotlin/kotlin-koans/blob/resolutions/src/iii_conventions/MyDate.kt) doesn't.

**Comment by svtk** [comment]
Fixed, thanks!
