### ISSUE TITLE
Gradle 3.0 in gradle-wrapper.properties file causing error while loading the project in Android Studio 3.0

### ISSUE THREAD

**Issue by p-sharma** [Kotlin/kotlin-koans#127]
While importing the repository in Android Studio 3.0.1 , got this error 

10:31 AM	Gradle sync failed: Could not initialize class org.jetbrains.kotlin.gradle.KotlinGradleModelBuilder Consult IDE log for more details (Help | Show Log) (354ms)

Update gradle distribution url to use gradle-4.1-all.zip, causes the error to go away.

**Comment by svtk** [comment]
#114 pr "Using latest Gradle release" merged
