### ISSUE TITLE
Task 31 : resolution doesn't pass test

### ISSUE THREAD

**Issue by geir** [Kotlin/kotlin-koans#128]
Caution - I'm a newbie.

for n31, my solution looks the same as the 'resolution' version, but doesn't pass the test I think because of the declarations of 

    operator fun Invokable.invoke(): Nothing = todoTask31()
    fun Invokable.getNumberOfInvocations(): Nothing = todoTask31()

in the test class.

Note that the resolution doesn't pass either, I believe for the same reason?  Can you give me a hint?  My solution is 

  class Invokable (private var count : Int = 0) {

     operator fun invoke() : Invokable {
         count++
         return this
     }

     fun getNumberOfInvocations() : Int = count
 } 

Apologies if I'm being an idiot.

**Comment by novaterata** [comment]
I agree

**Comment by the-icarus** [comment]
For me it was the same issue.
I have seen the same lines as you do. I guess what happens is that the two declarations you mention:
```kotlin
operator fun Invokable.invoke(): Nothing = todoTask31()
fun Invokable.getNumberOfInvocations(): Nothing = todoTask31()
```

will overwrite/replace the functions created in n31Invoice.kt
If those lines are removed, the tests will pass successfully. So I think in the resolution the two lines mentioned above should be removed.

**Comment by svtk** [comment]
The test class `N31InvokeKtTest` should be recompiled to pick up the changes in `n31Invoke.kt`. If it still calls extension functions declared in tests instead, it means it doesn't see the recent changes in the `Invokable` class.
There's no need to remove extension methods from the tests. If both member and extension with the same signature are available, the Kotlin compiler always chooses the member, so extensions in tests won't be called.
