### ISSUE TITLE
Identical product names in TestShop.kt

### ISSUE THREAD

**Issue by Kaens** [Kotlin/kotlin-koans#129]
val dotTrace = Product("DotTrace", 159.0)
val dotMemory = Product("DotTrace", 129.0)
https://github.com/Kotlin/kotlin-koans/blob/fcbd858b1cd27da4b40471271ecf2b5b3020bc0b/test/ii_collections/TestShop.kt
Is this as intended?

**Comment by svtk** [comment]
Thanks! Fixed
