### ISSUE TITLE
Task n22Fold clarification.

### ISSUE THREAD

**Issue by simo-andreev** [Kotlin/kotlin-koans#133]
https://github.com/Kotlin/kotlin-koans/blob/2e7ef9fee61390dd83cc12b98957d4bdf088a895/src/ii_collections/n22Fold.kt#L16

Might be better if it read something like:
    `// Return the set of products that were ordered by all of the customers `
Might be just me, but for quite a while I thought the returned collection should be ordered (as in 'organised') by `customer` somehow.

**Comment by svtk** [comment]
Thanks! Fixed to "Return the set of products that were ordered by each of the customers"
