### ISSUE TITLE
Upgrade to latest Gradle release version

### ISSUE THREAD

**Issue by Davio** [Kotlin/kotlin-koans#162]
Currently, Gradle is at version 4.10 while this repository uses 4.2.1.

It would be nice if the Gradle version of the wrapper and its corresponding build file would be upgraded to use the latest release version.

**Comment by Saladoc** [comment]
I second this. The gradle wrapper fails with jdk11 due to 4.2.1 not being able to resolve the version number `11.0.1`

**Comment by svtk** [comment]
Thanks! Updated
