### ISSUE TITLE
Migrate to JUnit 5

### ISSUE THREAD

**Issue by sw-samuraj** [Kotlin/kotlin-koans#174]
_JUnit 5_ is here for 1.5 year. Wouldn't be convenient to migrate from _JUnit 4_ up to the contemporary version of framework?

I've already did the migration in my fork of the project and the changes are relatively easy, mostly change of imports (e.g. [N00StartKtTest.kt](https://github.com/sw-samuraj/kotlin-koans/blob/master/test/i_introduction/_0_Hello_World/N00StartKtTest.kt)). I can prepare a pull request for this.

**Comment by svtk** [comment]
Thanks! Updated
