### ISSUE TITLE
Collections/Fold test on try.kotlinlang.org is incorrect

### ISSUE THREAD

**Issue by MaXal** [Kotlin/kotlin-koans#31]
On http://try.kotlinlang.org/ looks like Collections/Fold test is incorrect.

The following code is not acceptied:
```
// Return the set of products that were ordered by every customer
fun Shop.getProductsOrderedByAllCustomers(): Set<Product> = customers.fold(emptySet(), {
    partProduct, element ->
    partProduct + element.orders.flatMap { it.products}
})
```

and the test fails with the following message:
```
java.lang.AssertionError: 

Expected: ['IntelliJ IDEA Ultimate' for 199.0]
Actual: ['IntelliJ IDEA Ultimate' for 199.0, 'WebStorm' for 49.0, 'YouTrack' for 500.0]
    <click to see a difference>

    at org.junit.Assert.fail(Assert.java:93)
    at org.junit.Assert.failNotEquals(Assert.java:647)
    at org.junit.Assert.assertEquals(Assert.java:128)
    at org.junit.Assert.assertEquals(Assert.java:147)
    at TestFold.testGetProductsOrderedByAllCustomers(Test.kt:16)
```

The test looks invalid:
```
Assert.assertEquals(setOf(idea), testShop.getProductsOrderedByAllCustomers())
```
since according to description the set should contain all products from all customers.

**Comment by svtk** [comment]
Thanks! The function name was indeed ambiguous, so I renamed the function to 'getSetOfProductsOrderedByEveryCustomer'. In this case the test is correct.

**Comment by leoxs22** [comment]
Hello!

Sorry for commenting in an issue so old, but the text in the edutools plugin is showing the old method name. I'm not sure where to report it

![image](https://user-images.githubusercontent.com/9098977/58425616-9c63f600-8070-11e9-8268-323ae5338934.png)
