### ISSUE TITLE
Wrong documentation links for "Max; min" task

### ISSUE THREAD

**Issue by gabriel-fallen** [Kotlin/kotlin-koans#33]
On this page: http://try.kotlinlang.org/#/Kotlin%20Koans/Collections/Max%20min/Task.kt
"maxBy" link points to "max" page.

**Comment by svtk** [comment]
Fixed, thanks. Will be uploaded soon.

**Comment by gabriel-fallen** [comment]
Thank you!
The exercises were fun and engaging I enjoyed them. Great work. :)
