### ISSUE TITLE
Wrong documentation links for "Sort" task

### ISSUE THREAD

**Issue by gabriel-fallen** [Kotlin/kotlin-koans#34]
On this page: http://try.kotlinlang.org/#/Kotlin%20Koans/Collections/Sort/Task.kt
"sortBy" link points to nonexistent page. It should be named "sortedBy" and point to the corresponding page in documentation.
"sort" link points to correct page, but probably still should be named "sorted" and point to "sorted" page.

**Comment by svtk** [comment]
Fixed, thanks
