### ISSUE TITLE
Doesn't work with Android Studio 2.0 preview

### ISSUE THREAD

**Issue by hzsweers** [Kotlin/kotlin-koans#36]
Figure there's a change you guys might want to investigate. I get 237 errors and failure at compilation, all along the lines of

`Error:(5, 1) Kotlin: 'public fun todoTask0(): kotlin.Nothing' is already defined in i_introduction._0_Hello_World.Hello`

`Error:(7, 5) Kotlin: Redeclaration: idea`

This is happening with plugin version 1.0.0-beta-2429-IJ143-19

Full output here: https://gist.github.com/hzsweers/7e341269f824c05232e8

**Comment by cy6erGn0m** [comment]
Perhaps rebuild could workaround the issue

**Comment by hzsweers** [comment]
This happens on rebuild too, even after cleaning or reimporting the project.

**Comment by twbarber** [comment]
Was able to replicate with the following configuration:

Android Studio 2.0: 143.2443734
Kotlin JPS plugin version 1.0.0-beta-2429-IJ143-19

**Comment by twbarber** [comment]
I was able to solve this by using the 'VCS -> Checkout from Version Control' option in Android Studio. 

At first I tried importing the same local repository I was working on in IDEA, and got the same errors at compile time. Cloning the repository in the Android Studio projects folder via AS, and opening the version there appears to work just fine. I'm able to compile and run tests with no issues.
