### ISSUE TITLE
I'm a newbie, Need help

### ISSUE THREAD

**Issue by CodingPapi** [Kotlin/kotlin-koans#41]
Task 5.
        Copy the body of 'getPattern()' to the 'task5()' function
        and rewrite it in such a way that it matches '13 JUN 1992'.
        Use the 'month' variable.

I cannot pass the test in "i_introduction  _5_String_Templates"
How do I pass this using getPattern() and **‘month’** variable?

**Comment by svtk** [comment]
Hi, CodingPapi! The corresponding documentation pages can help you to understand what language features can be used. The reference to the documentation is in the beginning of the task description. If you're desperately stuck with some task, you can use 'show answer' button to move on.
