### ISSUE TITLE
no "kotlinc" documentation for including "util"

### ISSUE THREAD

**Issue by Patterner** [Kotlin/kotlin-koans#47]
I tried to compile `kotlin-koans/src/i_introduction/_0_Hello_World/HelloWorld.kt`
with `kotlinc HelloWorld.kt -include-runtime -d HelloWorld.jar`
but it fails:
`HelloWorld.kt:3:8: error: unresolved reference: util`
`import util.TODO`
`       ^`

I googled for an hour, read the documentation but I couldn't find out how to do that properly.

**Comment by svtk** [comment]
Hi Patterner! This function is declared in the `kotlinUtil.kt` file in the same project. That means you have to compile the whole project, not just one file. 

A convenient way to work with koans is through IDE (Intellij Idea, for example). In this case all the compilation goes automatically. You can check the online version http://try.kotlinlang.org/koans (the tasks are almost the same) as well.

**Comment by Patterner** [comment]
that was disappointing
