### ISSUE TITLE
Simplify solution to 23 - Compound Tasks

### ISSUE THREAD

**Issue by breun** [Kotlin/kotlin-koans#51]
I think the solution to 23 could be simplified by leaving out the `Customer.getOrderedProductsList()` extension function and just chaining two `flatMap` operations like this:

```
fun Shop.getNumberOfTimesProductWasOrdered(product: Product): Int {
    // Return the number of times the given product was ordered.
    // Note: a customer may order the same product for several times.
    return customers.flatMap { it.orders }.flatMap { it.products }.count { it == product }
}
```

**Comment by breun** [comment]
By the way, this next solution (which was my first try) also makes the test pass, but I guess this is not a correct solution, because it counts the number of orders that contain the product and I guess an order could contain a particular product more than once, but the test doesn't test for this case.

```
fun Shop.getNumberOfTimesProductWasOrdered(product: Product): Int {
    // Return the number of times the given product was ordered.
    // Note: a customer may order the same product for several times.
    return customers.flatMap { it.orders }.count { it.products.contains(product) }
}
```

**Comment by svtk** [comment]
Thanks! I've updated the solution (you're right, your version looks simple enough) and added the necessary test.
