### ISSUE TITLE
Wrong expected value for test 22 (fold) assert

### ISSUE THREAD

**Issue by YevgenijZ** [Kotlin/kotlin-koans#56]
Current:
assertEquals(setOf(idea), testShop.getSetOfProductsOrderedByEveryCustomer())
Correct:
assertEquals(setOf(idea, webStorm, youTrack), testShop.getSetOfProductsOrderedByEveryCustomer())

**Comment by svtk** [comment]
Hi! We're interested in a set of products ordered by _every_ customer here. That means each customer in the test example should have ordered a product, and only 'idea' is the product that our test customers both ordered.

**Comment by tmseiler** [comment]
This tripped me up too, I guess because of the wording. Unfortunately I don't have a suggestion that would help :(
