### ISSUE TITLE
What is "Kotlin Tool Window" on 35?

### ISSUE THREAD

**Issue by nelsonjchen** [Kotlin/kotlin-koans#58]
https://github.com/Kotlin/kotlin-koans/blob/4c1f92c49b247631abd9d7144c085301b5cbdf9c/src/iv_properties/_35_HowDelegatesWork.kt#L26-L26

```
    // Browse the Kotlin tool window in IntelliJ IDEA for details.
```

I'm not certain what this is. Is this related to #26? Is this supposed to be the bytecode viewer?

**Comment by svtk** [comment]
Yes. Now you can call an action "Show Kotlin Bytecode" instead (I've changed the mention as well).
