### ISSUE TITLE
Lesson1-task6 - Remove curly brackets because of string template around simple identifier

### ISSUE THREAD

**Issue by piotrek1543** [Kotlin/kotlin-koans#59]
I'd clicked on "Fill answer placeholders" to compare with my answer and  I saw this code:

```
val month = "(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)"

fun getPattern(): String = """\d{2} ${month} \d{4}"""

```

As I'd written my answer without these brackets and it worked as well as with them, I feel a bit confuse if using curly brackets in this exact example is correct. Do I need to write curly brackets in examples as above?

**Comment by svtk** [comment]
You're right, you can omit the curly braces and write `$month` directly (I'll update the answer to a simple form later). You use `${}` in string templates for more complicated expressions, like in `${month.length}`.

**Comment by piotrek1543** [comment]
Thanks for answer
