### ISSUE TITLE
Tests ok without doing anything in _27_Rangeto.kt

### ISSUE THREAD

**Issue by Ghalnas** [Kotlin/kotlin-koans#60]
Hello,

I've spotted a Test class that, I think shouldn't be ok.
The todo in `iii_conventions/_27_Rangeto.kt` asks for implementing the `MyDate.rangeTo()` function in MyDate.kt.
However, commenting it shows no compilation error, and the tests actually pass (see screenshot below).
I may understand why it works, but still think than, according to the Todo : 

> To make '..' work implement a 'MyDate.rangeTo()' extension function returning DateRange.

 it shouldn't.

![](http://puu.sh/pgoo6/56307b6ced.png)

**Comment by svtk** [comment]
Hi! That's ok. The task is to implement the `rangeTo` function on your own despite having the proper more generic function, an extension to `Comparable<T>`, in the standard library.

**Comment by Ghalnas** [comment]
Sure, i get it, my point was only the "to make '..' work" part, that i thought was not clear enough, as it already works without doing anything (unlike the previous ones that lead to compilation errors)
