### ISSUE TITLE
Missing explanation of how to setup in IntelliJ

### ISSUE THREAD

**Issue by SteffenIvanhoe** [Kotlin/kotlin-koans#63]
I would like to learn Kotlin with the help of the Koans but I'm new to IntelliJ and can not figure out how to setup the project such that I can execute something.

What I tried was first to open a project by specifying the directory of the Kotlin Koans. I expected a kind of project file to be found there. And indeed IntelliJ opened something and displayed a directory structure. 

But no way to execute something. Then I tried to create a new Kotlin project in the directory. This allowed me to specify the JRE and the libs used. Seemed logical but still no way to execute something. 

Then I tried to add a configuration. First I tried Kotlin. But I could not finish it because I don't know the main class. Then I tried to create JUnit based configuration. This gets me  "JUnit not found in module 'KotlinKoans'".

I'm still not able to use the code. Some words on how to set this up in IntelliJ would really be helpful. Otherwise Kotlin stays inaccessible to me.

**Comment by belovrv** [comment]
Hi, Steffen. For playing with Kotlin Koans in IntelliJ IDea you can use the Kotlin Edu plugin: https://blog.jetbrains.com/kotlin/2016/03/kotlin-educational-plugin/
It contains the Kotlin Koans puzzle and everything is configured out of the box./
See the video for instructions: https://youtu.be/0ponbfQhESY
The information about this plugin is missed on the site and koan's documentation, thanks for pointing it out.
