### ISSUE TITLE
Rewrite MyDate.kt code using functional paradigm

### ISSUE THREAD

**Issue by piotrek1543** [Kotlin/kotlin-koans#72]
Hi,

nowadays content of `MyDate.kt` is more objected-like and it does not look fancy (as it could): 

```kotlin
data class MyDate(val year: Int, val month: Int, val dayOfMonth: Int) : Comparable<MyDate>{
    override fun compareTo(other: MyDate): Int{
        if(year != other.year) return year - other.year
        if(month != other.month) return month - other.month
        return dayOfMonth - other.dayOfMonth
    }
}

operator fun MyDate.rangeTo(other: MyDate) = DateRange(this, other)
```
I think that better purpose for this `Kotlin` programming language course would be rewrite existing code using a functional programming paradign. Here's my solution:

```kotlin
data class MyDate(val year: Int, val month: Int, val dayOfMonth: Int) : Comparable<MyDate>{
    override fun compareTo(other: MyDate): Int = when {
        year != other.year -> year - other.year
        month != other.month -> month - other.month
        else -> dayOfMonth - other.dayOfMonth
    }
}

operator fun MyDate.rangeTo(other: MyDate) = DateRange(this, other)
```

I must agree that change is pretty small, but as you provide in `kotlin-koans` course typical functional structures like lambdas or recursion, maybe it would be better to keep this course and its code functional, than messing it with 'java-like' code. 

Although, I found fun in rewriting every `MyDate.kt` instance and that was good additional trainign :-D

Hope you would find useful.
Cheers!

**Comment by svtk** [comment]
The suggested solution for the 'comparison' task contains the version with 'when'. I've updated the extra examples as well (on http://try.kotlinlang.org/, the educational plugin will be updated later). This solution is already used in the koans version for IDE.

**Comment by piotrek1543** [comment]
> This solution is already used in the koans version for IDE.
Well, I've the latest version of IDEA Community with kotlin-edu plugin and I must confess that hadn't that solution until I changed it manually.

I checked the online version and you're right there is an update:

```kotlin
data class MyDate(val year: Int, val month: Int, val dayOfMonth: Int) : Comparable<MyDate> {
    override fun compareTo(other: MyDate) = when {
        year != other.year -> year - other.year
        month != other.month -> month - other.month
        else -> dayOfMonth - other.dayOfMonth
    }
}
```

Thanks for response.

**Comment by svtk** [comment]
Yes, the version with the kotlin-edu plugin is the slowest in terms of the update time. By "koans version for IDE" I meant this project (https://github.com/Kotlin/kotlin-koans) which can be used without the plugin, just in IDE. But please feel free to use whatever version you like, there're almost no differences between the tasks (the kotlin-edu plugin will be updated soon as well).
