### ISSUE TITLE
Cannot add extension with name 'kotlin', as there is an extension already registered with that name

### ISSUE THREAD

**Issue by MattFriedman** [Kotlin/kotlin-koans#73]
Just cloned and I get the following:

```
 ./gradlew test

FAILURE: Build failed with an exception.

* Where:
Build file '/workspace/kotlin-koans/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'kotlin-koans'.
> Failed to apply plugin [id 'kotlin2js']
   > Cannot add extension with name 'kotlin', as there is an extension already registered with that name.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.762 secs
```

**Comment by jelmew** [comment]
Same problem here aswell. It seemds the kotlin2js plugin has the same name?

**Comment by svtk** [comment]
The Kotlin Koans project doesn't use 'kotlin2js' at all. I can't reproduce this. 
Could you please create an issue (kotl.in/issue) describing what version of IDE you're using (IntelliJ IDEA or Android Studio with the version) and the version of the Kotlin plugin as well (can be found in Preferences -> Plugins).
Thank you!

**Comment by haslers** [comment]
This is an IntelliJ Problem. IntelliJ adds kotlin2js to the project if you try to configure Kotlin automatically within IntelliJ. For me, it helped to delete the kotlin2js dependency and re-import the project with gradle.

**Comment by BenLeggiero** [comment]
Thank you, @haslers! You helped me in a completely separate project, but this was the first result on Google 😄
