### ISSUE TITLE
Spurious line in Koan 25 Comparisons?

### ISSUE THREAD

**Issue by efung** [Kotlin/kotlin-koans#88]
Why is [this line](https://github.com/Kotlin/kotlin-koans/blob/2eb00cd808e634d749b114fe4d9ce409b80d39c2/test/iii_conventions/_25_Comparison.kt#L24) present, from `test/iii_conventions/_25_Comparison.kt`:

        operator fun MyDate.compareTo(other: MyDate): Int = todoTask25()

I think its presence allows the test code to compile, but if you add the operator extension function to `MyDate.kt`, this line in the test file is still used so the test is still broken. By commenting it out, the test passed for me.

**Comment by svtk** [comment]
You're right, this line makes the tests compile. The task contains "Make the class 'MyDate' implement 'Comparable'" which implies that you won't create an extension. If you create an extension, you can remove the extension in tests.
