### ISSUE TITLE
README

### ISSUE THREAD

**Issue by benunderwood** [Kotlin/kotlin-koans#89]
Thank you for the project! 
I've just got it working in Android Studio, and am now learning Kotlin - but it took a bit of playing around with to get there.
I think "To build the project and run tests use 'test' task on Gradle panel." in the README could do with expanding a bit; specifically that "test" is found in Koans->Tasks->verification->test.  Also "Gradle panel" was a bit vague. I didn't even notice it there, on the right of my screen, to begin with!
Cheers,
Ben.

**Comment by svtk** [comment]
Thanks for pointing this out! Changed the reference to Gradle tasks description here: https://github.com/Kotlin/kotlin-koans/commit/d1700aa6757a21209015e1726ec1e306a09e6484.
