### ISSUE TITLE
Jump to tests

### ISSUE THREAD

**Issue by ae-dg** [Kotlin/kotlin-koans#97]
Hi,

I'm trying to use Navigate -> Test and it just pops up the "Create New Test..." dialog. Can the koans be configured so this works to be able to jump back and forth between code and test?

**Comment by singlepig** [comment]
@ae-dg 
Is 'ctrl + tab' works for you?

**Comment by svtk** [comment]
I've renamed the files to make it work. 

@singlepig This is another feature, 'ctrl+tab' should work as well. See the comment here: https://github.com/Kotlin/kotlin-koans/commit/3887c0d163b2f08aa92f04eb66218ed8254b3977
